"""Initial migration.

Revision ID: 67d972f827ee
Revises: 8386bec5d578
Create Date: 2021-07-13 15:27:48.598364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d972f827ee'
down_revision = '8386bec5d578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_model', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('users_model', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_model', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users_model', 'password_hash')
    # ### end Alembic commands ###
