"""empty message

Revision ID: 832bab27f1a2
Revises: 115d920f9b0c
Create Date: 2021-07-17 11:45:42.454177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832bab27f1a2'
down_revision = '115d920f9b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_category_id_fkey', 'events', type_='foreignkey')
    op.drop_table('events_categories')
    op.drop_column('events', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_category_id_fkey', 'events', 'events_categories', ['category_id'], ['id'])
    op.create_table('events_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='events_categories_pkey')
    )
    # ### end Alembic commands ###
