"""empty message

Revision ID: b7a48a826b2a
Revises: 832bab27f1a2
Create Date: 2021-07-17 12:06:59.097077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a48a826b2a'
down_revision = '832bab27f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_important')
    # ### end Alembic commands ###
