"""empty message

Revision ID: f34efe29c49c
Revises: b7a48a826b2a
Create Date: 2021-07-20 16:00:34.115141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34efe29c49c'
down_revision = 'b7a48a826b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'poll_options', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll_options', type_='unique')
    # ### end Alembic commands ###
