"""add title to fee and set default payment none

Revision ID: f5a6ceeec585
Revises: d20491d3e9c0
Create Date: 2021-07-22 10:53:09.280506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a6ceeec585'
down_revision = 'd20491d3e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fees', sa.Column('title', sa.String(length=50), nullable=True))
    op.alter_column('fees', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fees', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('fees', 'title')
    # ### end Alembic commands ###
