from app.views.login_view import Login
from app.views.notices_view import Notices
from app.views.users_view import Users
from app.views.poll_options_view import PollOptions
from app.views.polls_view import Polls
from app.views.votes_view import PollsVotes
from app.views.events_view import Events
from app.views.invitations_view import Invitations
from app.views.homes_view import Homes
